### PR TITLE
feat: Update for regular icons set to 4.0.0 version

### PR DESCRIPTION
**Pull request by robothemes**
Hi. I use Material Icons set in our current project and it definitely misses new icons so I decided to update it to the latest version. It will be great if you can update your project.

### CODE REVIEW

**Comment by Angelmmiguel** [comment]
Hey @robothemes!

Thank you for the PR. This project was not updated for a while, so updating it to the latest material icons versions is quite nice. Before accepting this PR, I need to work on bringing back the CI so everything is properly tested.

I created #37 and a v4.0.0 milestone to track this effort. I plan to cover several issues that have been open for some time as part of this release.

I will try to add the CI in a few days, so we can properly test and merge these changes. Will ping you when it's ready, but you will need to rebase your fork and apply same changes again so the CI is taken into account.

Thank you!

**Comment by Angelmmiguel** [comment]
Hello @robothemes!

Sorry for the delay here. I just finished some pending tasks and this PR is unblocked now. You would need to rebase your changes as some changes are no longer required:

* The `Rakefile` has been removed (#40)
* `app/assets/stylesheets/material_icons_unicode.css.erb` has been deleted too (#40)

Then, the PR is good to go!

**Comment by Angelmmiguel** [comment]
Btw, this PR closes #39

**Comment by hawkes69** [comment]
Hey, @Angelmmiguel I'm in the process of moving my app off the material_design_icons gem which is now deprecated. I'd like to use this gem but about half the icons I tried to use were not supported. Any idea when this change will be ready?

**Comment by Angelmmiguel** [comment]
Hello @hawkes69,

I'm glad you find `material_icons` useful! Once the PR is completed, I will work on updating the documentation and bumping the version. I still need to also do some more testing to confirm the library works as expected.

I cannot ensure you a deadline, but I would like to have the next version published by the end of next week :).

**Comment by hawkes69** [comment]
Thanks for the quick response @Angelmmiguel. I'm not in a huge rush I just wanted a ballpark so this is perfect. Thanks for the help!

**Comment by hawkes69** [comment]
@Angelmmiguel  do you have any update on when this will be done?

**Review by Angelmmiguel — CHANGES_REQUESTED** [review]
Thanks for the final PR @robothemes! 

The PR LGTM. I was planning to drop EOT as I wanted to drop support for IE. So, it's fine to remove it in this PR too. I will create a separate task to remove it and associate it here.

However, there's a test that actually checks the presence of the EOT file, so you would need to remove it too: https://github.com/Angelmmiguel/material_icons/blob/master/spec/requests/material_icons_fonts_spec.rb#L7.

We're closer to close this @hawkes69 :)

**Review by Angelmmiguel — APPROVED** [review]
LGTM!

**Pull request merged**
